### ISSUE TITLE
Radbot Radio

### ISSUE THREAD

**Issue by wintersteiger** [opentrv/OTWiki#2]
Not sure this is the right place to start. Is there an official OpenTRV forum for tech questions elsewhere?

I recently bought a Radbot and I'm trying to pick up it's bi-minutely radio chirps, but I haven't had any luck so far. Do Radbots indeed send those signals and are they at 868.35/OOK/5kbps and are they just to weak to be picked up by my "exquisite gear" (cheapo CC1101)? I have no trouble receiving FSK from my Evohome devices though.

**Comment by DamonHD** [comment]
Hi!

There is an OpenTRV dev mailing list which I can put you on if you wish (drop me a line at d AT hd DOT org).

Note that Radbot, based on newer OpenTRV code, is on a more robust FSK carrier/scheme now, and comms are encrypted.  (Both the channel details and the encryption scheme are published.)

Rgds

Damon

**Comment by wintersteiger** [comment]
Awesome, thanks for the quick reply, you saved me a bunch of time! Should those documents be available on the Vestemi website?

**Comment by DamonHD** [comment]
I think that the right place is the OpenTRV repos, since they are part of the open source base.

Would you like links to the items that I mentioned?

Rgds

Damon

**Comment by wintersteiger** [comment]
Thanks! Over the weekend I was able to find all the pieces of the puzzle. I did have to heat up the soldering iron to inject a new key into the Radbot (thanks for keeping the silkscreen pin labels!), but that didn't take very long at all. I am now able to monitor all the O frames and I get them decoded and authenticated.

The remaining issue that I have is that my radio has very poor reception (or the Radbot has weak TX), I basically have to keep it within a meter of the Radbot to not drop frames. It's probably just a wrong setting in my radio config though.

Finding the information about the statistics wasn't hard, but a bit annoying; it would be nice if there were a single page that lists all the statistics that are reported and their units, etc. Apart from that, a pointer that points to the exact version of the code that runs on the Radbot would be nice, but for my purposes all of them are very similar.

**Comment by DamonHD** [comment]
Well done you!

Note that the batteries are part of the antenna, so I'd expect less good performance if they are not fitted (I'm assuming that you are also powering your device via soldered-on leads.)

While we do see slightly less good TX from the Radbot than the TRV1, and from a whip antenna, it's not that much worse I think it's fair to say.

Rgds

Damon

**Comment by Denzo77** [comment]
I'm not sure exactly what you mean by statistics, but have you seen this page?
https://github.com/opentrv/OTWiki/wiki/Data-Formats

**Comment by wintersteiger** [comment]
Yes, that's exactly what I meant, thanks! It didn't occur to me that this could be in the wiki; I only looked for it in header files :-)

**Comment by wintersteiger** [comment]
Thanks for the hint about the batteries being part of the antenna! I did power the Radbot via soldered-on power leads when I injected the key, but the rest of the time I run it on batteries. The batteries point toward the wall and radiator, so I can read the dial, I guess that's not ideal either. I should really run some tests with a power supply, just to see whether it makes a difference.

**Comment by DamonHD** [comment]
Please do let me know your results: more data points always welcome!

Rgds

Damon
